### ISSUE TITLE
Sometimes 'not opened'-Error when client is closed

### ISSUE THREAD

**Issue by Nuri0** [bkw/node-dronestream#16]
Hey @bkw,
I've written a http-server that is delivering some frontend, which is among other things using your dronestream (great work by the way!). Mostly it is working just fine but sometimes it (or rather WebSocket) just throws an 'not opened'-error:

```
..\dronestream\node_modules\ws\lib\WebSocket.js:181
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (C:\Users\Max\Documents\UNI\MFS-Git\AID\server\node_modules\dronestream\node_modules\ws\lib\WebSocket.js:181:16)
    at C:\Users\Max\Documents\UNI\MFS-Git\AID\server\node_modules\dronestream\lib\stream.js:46:24
    at Array.forEach (native)
    at PaVEParser.<anonymous> (C:\Users\Max\Documents\UNI\MFS-Git\AID\server\node_modules\dronestream\lib\stream.js:45:21)
    at emitOne (events.js:77:13)
    at PaVEParser.emit (events.js:169:7)
    at PaVEParser.sendData (C:\Users\Max\Documents\UNI\MFS-Git\AID\server\node_modules\dronestream\lib\PaVEParser.js:117:14)
    at PaVEParser.write (C:\Users\Max\Documents\UNI\MFS-Git\AID\server\node_modules\dronestream\lib\PaVEParser.js:87:18)
    at TcpVideoStream.<anonymous> (C:\Users\Max\Documents\UNI\MFS-Git\AID\server\node_modules\dronestream\lib\stream.js:42:20)
    at emitOne (events.js:77:13)
```

I couldn't reproduce the error in a specific way, but after repeatedly opening and closing the client, after some time it just happens. Could it be the version of WebSocket? Dronestream is currently using version `"0.4.32"` of WebSocket while the latest version is `"0.8.0"`.

**Comment by bkw** [comment]
you are most probably right. This module has not been given much attention lately. Could you try updating ws and supply a pr if it works? That would be awesome!

**Comment by Nuri0** [comment]
Sorry for the long wait. I couldn't get my hand on the drone for the last two weeks.

I tried updating the ws-module, but it didn't fix the error. What I think is happening is that we have a case of some race condition. The browsertab has already been closed on client-side, but in `stream.js` it can happen, that some video data is send via a socket just slightly before it is closed. I tried changing line 46 in `stream.js` from

```
socket.send(data, {binary: true});
```

to

```
try {
    socket.send(data, {binary: true});
} catch(err) {
    console.log('Websocket error: %s', err);
}
```

and just output the error, which is causing the problem. So instead of crashing the application I just get `Websocket error: Error: not opened` on the console. If you are OK with this kind of fix (do you still want Websocket to be updated?) I could commit it and submit a pull request.

**Comment by bkw** [comment]
Adding the catch certainly makes sense, thanks!

For the ws update, I'd appreciate a separate PR if that's not too much to ask. Thanks for your help with this!

**Comment by Nuri0** [comment]
No problem!
Just some small technical question: For two pull requests do I need to fork this twice (probably not) or do I just make two commit on my fork and then do a pull requests for each of them?

**Comment by bkw** [comment]
You can stack them on top of each other, as long as they don't touch the same files, it doesn't matter.

**Comment by Nuri0** [comment]
After some playing with branches, git's cherry-pick I finally got the pull requests to work (first time I am doing something like that). I hope it's like you prefer it.

**Comment by bkw** [comment]
Awesome, thanks! I merged both, but publishing to npm will have to wait a bit I'm afraid. Feel free to remind me if didn't do this over the weekend.
Thanks again for your contribution!
